<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/07/05 14:12:40
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
