<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/05 14:12:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfony',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
